"""
================================================================================
DATA CLEANING SCRIPT: dim_products.csv
================================================================================
Tools: Pandas, NumPy, Matplotlib
Author: Generated by Kimi
Date: 2026-07-03

DESCRIPTION:
    Cleans a product dimension table by addressing three data quality issues:
    1. Missing category/subcategory/maintenance for 7 pedal products
    2. Missing product_line for 17 generic component parts
    3. Zero cost values for 2 HL Road Frame size-58 variants

OUTPUT:
    - dim_products_cleaned.csv (cleaned dataset)
    - data_cleaning_report.png (visualization report)
================================================================================
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ============================================================================
# STEP 1: LOAD DATA
# ============================================================================

# Load the raw product dimension table
df = pd.read_csv('data/raw/dim_products.csv')

print("=" * 70)
print("ORIGINAL DATA PROFILE")
print("=" * 70)
print(f"Shape: {df.shape}")
print(f"Column Info:")
print(df.dtypes)
print(f"Missing Values per Column:")
print(df.isnull().sum())
print(f"Duplicated Rows: {df.duplicated().sum()}")


# ============================================================================
# STEP 2: INVESTIGATE ISSUE 1 — Missing category/subcategory/maintenance
# ============================================================================

print("\n" + "=" * 70)
print("INVESTIGATION 1: Missing category/subcategory/maintenance")
print("=" * 70)

# Identify rows with missing category data
missing_cat = df[df['category'].isnull()]
print(f"\nRows with missing category/subcategory/maintenance: {len(missing_cat)}")
print("\nProduct Numbers:", missing_cat['product_number'].tolist())
print("\nProduct Names:", missing_cat['product_name'].tolist())

# Verify: All start with PD- (pedals)
all_pd = missing_cat['product_number'].str.startswith('PD-').all()
print(f"\nAll product_numbers start with 'PD-': {all_pd}")

# Check Components category maintenance distribution for imputation rationale
components_mask = df['category'] == 'Components'
components_maintenance = df.loc[components_mask, 'maintenance'].value_counts()
print(f"\nComponents category 'maintenance' distribution:")
print(components_maintenance)
yes_pct = components_maintenance.get('Yes', 0) / components_mask.sum() * 100
print(f"Mode ('Yes') percentage: {yes_pct:.1f}%")


# ============================================================================
# STEP 3: INVESTIGATE ISSUE 2 — Missing product_line
# ============================================================================

print("\n" + "=" * 70)
print("INVESTIGATION 2: Missing product_line")
print("=" * 70)

missing_line = df[df['product_line'].isnull()]
print(f"\nRows with missing product_line: {len(missing_line)}")
print("\nProduct Names:")
for name in missing_line['product_name'].tolist():
    print(f"  - {name}")

# Check existing 'Other Sales' usage for imputation rationale
other_sales = df[df['product_line'] == 'Other Sales']
print(f"\nExisting 'Other Sales' product_line count: {len(other_sales)}")
print("Examples of existing 'Other Sales' products:")
print(other_sales['product_name'].head(10).tolist())


# ============================================================================
# STEP 4: INVESTIGATE ISSUE 3 — cost = 0
# ============================================================================

print("\n" + "=" * 70)
print("INVESTIGATION 3: cost = 0")
print("=" * 70)

zero_cost = df[df['cost'] == 0]
print(f"\nRows with cost = 0: {len(zero_cost)}")
print(zero_cost[['product_key', 'product_number', 'product_name', 'cost', 'category', 'subcategory']].to_string())

# Check all HL Road Frame costs for same-product-family imputation
hl_road = df[df['product_name'].str.contains('HL Road Frame', na=False)]
print(f"\n\nAll 'HL Road Frame' products:")
print(hl_road[['product_key', 'product_number', 'product_name', 'cost']].sort_values('product_number').to_string())

hl_road_nonzero = hl_road[hl_road['cost'] > 0]
print(f"\nHL Road Frame non-zero costs: {hl_road_nonzero['cost'].unique()}")
print(f"All non-zero HL Road Frame costs are 869: {(hl_road_nonzero['cost'] == 869).all()}")


# ============================================================================
# STEP 5: APPLY ALL FIXES
# ============================================================================

print("\n" + "=" * 70)
print("APPLYING DATA CLEANING FIXES")
print("=" * 70)

# Make a copy to preserve original data
df_clean = df.copy()

# --- FIX 1: Missing category/subcategory/maintenance for pedals ---
# Rationale: All product_numbers start with 'PD-' = pedals. Pedals are components.
#            84.3% of Components have maintenance='Yes' (mode imputation).
pedal_mask = df_clean['product_number'].str.startswith('PD-', na=False)
print(f"\nFIX 1: Pedals (PD-*) — {pedal_mask.sum()} rows")
print(f"  Before: category={df_clean.loc[pedal_mask, 'category'].isnull().sum()} nulls, "
      f"subcategory={df_clean.loc[pedal_mask, 'subcategory'].isnull().sum()} nulls, "
      f"maintenance={df_clean.loc[pedal_mask, 'maintenance'].isnull().sum()} nulls")

df_clean.loc[pedal_mask, 'category'] = 'Components'
df_clean.loc[pedal_mask, 'subcategory'] = 'Pedals'
df_clean.loc[pedal_mask, 'maintenance'] = 'Yes'

print(f"  After:  category='Components', subcategory='Pedals', maintenance='Yes'")

# --- FIX 2: Missing product_line for generic parts ---
# Rationale: These are generic parts (Fork, Headset, Chain, etc.) not tied to
#            a specific bike line. 'Other Sales' already exists for this purpose.
missing_line_mask = df_clean['product_line'].isnull()
print(f"\nFIX 2: Missing product_line — {missing_line_mask.sum()} rows")
print(f"  Before: product_line null count = {missing_line_mask.sum()}")

df_clean.loc[missing_line_mask, 'product_line'] = 'Other Sales'

print(f"  After:  product_line = 'Other Sales'")
print(f"  Products affected: {df_clean.loc[missing_line_mask, 'product_name'].tolist()}")

# --- FIX 3: cost = 0 for HL Road Frame size 58 ---
# Rationale: All other HL Road Frame variants (all sizes, all colors) cost $869.
#            Same-product-family imputation is the strongest evidence.
zero_cost_mask = df_clean['cost'] == 0
print(f"\nFIX 3: Zero cost HL Road Frames — {zero_cost_mask.sum()} rows")
print(f"  Before: cost = {df_clean.loc[zero_cost_mask, 'cost'].tolist()}")

df_clean.loc[zero_cost_mask, 'cost'] = 869

print(f"  After:  cost = 869 (same-product-family match)")
print(f"  Products: {df_clean.loc[zero_cost_mask, 'product_name'].tolist()}")


# ============================================================================
# STEP 6: POST-CLEANING VALIDATION
# ============================================================================

print("\n" + "=" * 70)
print("POST-CLEANING VALIDATION")
print("=" * 70)

print(f"\nShape: {df_clean.shape} (unchanged)")
print(f"\nMissing Values per Column:")
print(df_clean.isnull().sum())
print(f"\nDuplicated Rows: {df_clean.duplicated().sum()}")
print(f"\nZero cost rows remaining: {(df_clean['cost'] == 0).sum()}")

# Verify pedal fix
pedals = df_clean[df_clean['product_number'].str.startswith('PD-', na=False)]
print(f"\nPedal rows — category: {pedals['category'].unique()}, "
      f"subcategory: {pedals['subcategory'].unique()}, "
      f"maintenance: {pedals['maintenance'].unique()}")

# Verify product_line fix
print(f"\nNull product_line remaining: {df_clean['product_line'].isnull().sum()}")

# Verify cost fix
print(f"\nHL Road Frame size 58 costs: "
      f"{df_clean[df_clean['product_number'].isin(['FR-R92B-58', 'FR-R92R-58'])]['cost'].tolist()}")


# ============================================================================
# STEP 7: VISUALIZATION REPORT
# ============================================================================

fig, axes = plt.subplots(2, 2, figsize=(16, 14))
fig.suptitle('Data Cleaning Report: dim_products.csv', fontsize=16, fontweight='bold', y=1.02)

# --- Plot 1: Before vs After Missing Values ---
ax1 = axes[0, 0]
columns = ['category', 'subcategory', 'maintenance', 'product_line']
before = [7, 7, 7, 17]
after = [0, 0, 0, 0]

x = np.arange(len(columns))
width = 0.35
bars1 = ax1.bar(x - width/2, before, width, label='Before Cleaning', color='#e74c3c', edgecolor='black')
bars2 = ax1.bar(x + width/2, after, width, label='After Cleaning', color='#2ecc71', edgecolor='black')

ax1.set_ylabel('Missing Count', fontsize=11)
ax1.set_title('Missing Values: Before vs After', fontsize=13, fontweight='bold')
ax1.set_xticks(x)
ax1.set_xticklabels(columns, fontsize=10)
ax1.legend()
ax1.set_ylim(0, 22)

for bar in bars1:
    ax1.annotate(f'{int(bar.get_height())}',
                 xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                 ha='center', va='bottom', fontsize=10, fontweight='bold')
for bar in bars2:
    ax1.annotate(f'{int(bar.get_height())}',
                 xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                 ha='center', va='bottom', fontsize=10, fontweight='bold')

# --- Plot 2: Cost Distribution (HL Road Frame fix) ---
ax2 = axes[0, 1]
sizes = ['44', '48', '52', '58', '62']
orig_costs = [869, 869, 869, 0, 869]
clean_costs = [869, 869, 869, 869, 869]

x2 = np.arange(len(sizes))
ax2.bar(x2 - 0.2, orig_costs, 0.35, label='Before (size 58 = 0)', color='#e74c3c', edgecolor='black')
ax2.bar(x2 + 0.2, clean_costs, 0.35, label='After (size 58 = 869)', color='#2ecc71', edgecolor='black')

ax2.set_ylabel('Cost ($)', fontsize=11)
ax2.set_title('HL Road Frame Cost by Size: Before vs After', fontsize=13, fontweight='bold')
ax2.set_xticks(x2)
ax2.set_xticklabels([f'Size {s}' for s in sizes], fontsize=10)
ax2.legend()
ax2.set_ylim(0, 1000)

for i, (o, c) in enumerate(zip(orig_costs, clean_costs)):
    ax2.annotate(f'${o}', xy=(i - 0.2, o), ha='center', va='bottom', fontsize=9, fontweight='bold')
    ax2.annotate(f'${c}', xy=(i + 0.2, c), ha='center', va='bottom', fontsize=9, fontweight='bold')

# --- Plot 3: Subcategory Distribution (highlighting new Pedals) ---
ax3 = axes[1, 0]
subcat_counts = df_clean['subcategory'].value_counts().sort_values(ascending=True)
colors = ['#3498db' if s != 'Pedals' else '#f39c12' for s in subcat_counts.index]
bars3 = ax3.barh(subcat_counts.index, subcat_counts.values, color=colors, edgecolor='black')
ax3.set_xlabel('Count', fontsize=11)
ax3.set_title('Subcategory Distribution (Pedals = NEW)', fontsize=13, fontweight='bold')

for bar in bars3:
    ax3.annotate(f'{int(bar.get_width())}',
                 xy=(bar.get_width(), bar.get_y() + bar.get_height()/2),
                 ha='left', va='center', fontsize=9, fontweight='bold',
                 xytext=(3, 0), textcoords='offset points')

# --- Plot 4: Product Line Distribution ---
ax4 = axes[1, 1]
line_counts = df_clean['product_line'].value_counts()
colors4 = ['#9b59b6', '#3498db', '#e74c3c', '#2ecc71', '#f39c12']
wedges, texts, autotexts = ax4.pie(
    line_counts.values, labels=line_counts.index, autopct='%1.1f%%',
    colors=colors4, startangle=90, explode=[0.02]*len(line_counts),
    textprops={'fontsize': 10}
)
ax4.set_title('Product Line Distribution', fontsize=13, fontweight='bold')

# Highlight the newly assigned "Other Sales"
for i, label in enumerate(line_counts.index):
    if label == 'Other Sales':
        autotexts[i].set_fontweight('bold')
        autotexts[i].set_fontsize(11)

plt.tight_layout()
plt.savefig('data_cleaning_report.png', dpi=150, bbox_inches='tight')
plt.show()
print("\nVisualization saved to: data_cleaning_report.png")


# ============================================================================
# STEP 8: SAVE CLEANED DATA
# ============================================================================

df_clean.to_csv('data/cleaned/dim_products_cleaned.csv', index=False)

print("\n" + "=" * 70)
print("CLEANING COMPLETE")
print("=" * 70)
print(f"\nCleaned dataset saved to: dim_products_cleaned.csv")
print(f"Final shape: {df_clean.shape}")
print(f"Missing values: {df_clean.isnull().sum().sum()}")
print(f"Zero costs: {(df_clean['cost'] == 0).sum()}")
print(f"Duplicates: {df_clean.duplicated().sum()}")
